//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int IdProducto { get; set; }
        public string Fert { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string NumeroDeSerie { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Tipo Tipo1 { get; set; }
    }
}
